### ISSUE TITLE
Can run flex

### ISSUE THREAD

**Issue by yepher** [mothran/flex_hackrf#1]
I am runniing Mac OSX 10.9 and installed gnuradio 3.7 with MacPorts

When I try and run this script I get the following output:

```
[flex_hackrf (master)]$ python flex.py 
Traceback (most recent call last):
  File "flex.py", line 24, in <module>
    from gnuradio import gr, gru, optfir, eng_notation, blks2, pager
  File "/usr/local/lib/python2.7/site-packages/gnuradio/gr/__init__.py", line 27, in <module>
  File "/usr/local/lib/python2.7/site-packages/gnuradio/gr/gnuradio_core.py", line 23, in <module>
  File "/usr/local/lib/python2.7/site-packages/gnuradio/gr/gnuradio_core_runtime.py", line 28, in <module>
  File "/usr/local/lib/python2.7/site-packages/gnuradio/gr/gnuradio_core_runtime.py", line 20, in swig_import_helper
ImportError: No module named _gnuradio_core_runtime
```

This script seems to work just fine:

```
osmocom_fft -a hackrf
```

Any thoughts on what might be wrong?

**Comment by mothran** [comment]
Unfortunately I prototyped this with gnuradio 3.6.   When I did try and run it with with 3.7 I hit a different error.  Let me run a clean build on my machine.  I don't have access to a Mac so you might be a bit on your own with the ports version.  If you find anything, I will gladly accept a patch or pull req.
